#!/bin/bash
# --- dbconfig.sh ---
# usage usage ./dbconfig.sh [dev | restart | deploy | seed]
#
# richard l. gregg
# june 11, 2024
#
if [[ -z $1 ]]
then
  mode="deploy"
else
  mode="${1}"
fi

case ${mode} in
  "dev")
    # Development use only. Creates, migrates and seeds database
    npx prisma migrate dev --name saasmvp --schema=./database/schema.prisma
    exit 0
    ;;
  "restart")
    # Production use only. Resets database. Destructive. (creates database and tables, seeds)
    npx prisma migrate reset --schema=./database/schema.prisma
    exit 0
    ;;
  "deploy")
    # Production use only. Applies new migrations, no seeding
    npx prisma migrate deploy --schema=./database/schema.prisma
    exit 0
    ;;
  "seed")
    # Production or development use. Seeds or re-seeds database. Existing data left intact.
    #
    # The prisma client must have been generated prior to use. In development this is
    # done automatically. In production, the prisma client is generated by running
    # the ''./dbconfig.sh restart' command first which is done on initial install.
    npx prisma db seed
    exit 0
    ;;
  *)
    echo "usage ./dbconfig.sh [dev | restart | deploy | seed]"
    exit 1
    ;;
esac
 